config/routes.rb
Rails.application.routes.draw do

	get '/login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	
  resources :users, except: [:index, :edit, :show]
  get '/profile/edit', to: 'user#edit', as: 'edit_profile'
  get '/profile/close', to: 'user#close', as: 'close_profile'
  resources :brays
  root 'brays#index'
end

app/models/bray.rb
class Bray < ActiveRecord::Base
	belongs_to :user
	validates :body. pressence: true, length: { maximum: 160 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :brays, dependent: :destroy
	validates :password, confirmation: true
	validates_uniqueness_of :username, :email
	validates_presence_of :username, :email, :lname, :fname
	validates :password, presence: true, on: :create
	validates :password_confirmation, presence: true, on: :create
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def current_user
  	session[:user_id] ? User.find(sessions[:user_id]) : nil
  end

  def authenticate_user!
  	redirect_to login_path unless current_user
  end
end

app/controllers/brays_controller.rb
class BraysController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]
	def index
		@brays = Bray.all
	end

	def new
		@bray = Bray.new
	end

	def edit
	end

	def show
		@bray = Bray.find(params[:id])
	end

	def create
		@bray = Bray.new(params.require(:bray).permit(:body).merge(user:current_user))

		if @bray.save
			redirect_to root_path, notice: "New bray"
		else
			render :new
	end

	def update
	end

	def destroy
		@bray = Bray.find(params[:id])
		@bray.destroy
		redirect_to root_path, alert: "Bray deleted"
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@bray = Bray.new
	end

	def create
		@user = User.find_by_email(params[:email])
		if @user and @user.password == params[:password]
			session[:user_id] = @user.user_id
			redirect_to @user, notice: "Successfully logged in"
		else
			flash[:alert] = "Please try again"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: "You have been logged out."
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :update, :destroy]

	def new
		@user = User.new
	end

	def edit
		@user = current_user
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user, notice: "New Account Created"
		else
			render :new
		end
	end

	def update
		@user = current_user
		if @user.update(user_params)
			redirect_to @user, notice: "Profile Updated"
		else
			render :edit
		end
	end

		def destroy
		@user = current_user
		@user.destroy
		session[:user_id] = nil
		redirect_to root_path, notice: "Your account has been deleted"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
def current_user
  	session[:user_id] ? User.find(sessions[:user_id]) : nil
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brays/_bray.html.erb
<div class="bray">
	<h3><%= bray.body %></h3>
	<p>posted <% time_ago_in_words(bray.created_at) %> by
	<p><%= link_to bray.user.username, bray.user %>
		<% if current_user and current_user == bray.user %>
		| <%= link_to 'X', bray, method: :delete %>
		<% end %>
	</p>
</div>

app/views/brays/index.html.erb
<h3>Recent Brays</h3>
<%= render @brays %>

app/views/brays/new.html.erb
<h1>New Bray!</h1>

<%= form_for @bray do |f| %>
	<% if @bray.errors.any? %>
		<% @bray.errors.full_messages.each do | error | %>
		<p><%= error %></p>
		<% end %>
	<% end %>

	<div>
		<%= f.text_area :body, placeholder: "Write your bray here" %>
	</div>
	<div>
		<%= f.submit "Bray!" %>
	</div>
<% end %>

app/views/brays/show.html.erb
<%= render partial: 'bray', locals: { bray: @bray } %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
	<title>Neigh</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	
	<%= render 'shared/header' %>

	<main>
		<%= flash[:notice] if flash[:notice] %>
		<%= flash[:alert] if flash[:alert] %>
		
		<%= yield %>
	</main>

</body>
</html>

app/views/shared/_header.html.erb
<header>
	<h3><%= link_to 'Neigh', root_path %></h3>
	<nav>
		<ul>
			<% if current_user %>
				<li>Hello <%= current_user.username %></li>
				<li><%= link_to 'new bray', new_bray_path %></li>
				<li><%= link_to 'edit profile', edit_profile_path %></li>
				<li><%= link_to 'logout', logout_path, method: :delete %></li>
			<% else %>
				<li><%= link_to 'sign in', login_path %></li>
				<li><%= link_to 'sign up', new_user_path %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/users/new.html.erb
<h1>Sign up below!</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do | error | %>
		<p><% error %></p>
	<% end %>

	<div>
		<%= f.label :username %>
		<%= f.text_field :username %>
	</div>
	<div>
		<%= f.label :fname, "First Name" %>
		<%= f.text_field :fname %>
	</div>
	<div>
		<%= f.label :lname, "Last Name" %>
		<%= f.text_field :lname %>
	</div>
	<div>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</div>
	<div>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div>
		<%= f.submit "Sign up" %>
	</div>
	<% end %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<section>
	<h3><%= @user.username %>'s Details</h3>
	<ul>
		<li> <% @user.fname %> <% @user.lname %> </li>
	</ul>
</section>

app/views/users/user.html.erb
<h1>Hello <%= current_user.fname %></h1>

<h3>Below are your posts</h3>